# Generated by Django 4.2.7 on 2023-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveAcumulador', models.CharField(max_length=255)),
                ('QR', models.ImageField(upload_to='public/qrs')),
            ],
        ),
    ]
