# Generated by Django 4.2.7 on 2023-11-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_qr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
